POST http://localhost:3003/api/users HTTP/1.1
Accept: application/json
Content-Type: application/json
Content-Length: 60

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}